### ISSUE TITLE
2023-05-11 todo list

### ISSUE THREAD

**Issue by Junseongparkme** [Junseongparkme/web#9]
- [x] 포스팅 글 색상 바꾸기
- [x] #10
- [x] 포스팅 태그에 링크 걸어서 카테고리별 검색 결과로 이동시키기
- [x] 각 포스팅마다 메인 화면으로 이동하는 버튼 추가하기
